# BeeNames
#
debug: false
names:
- 'Meagan'
- 'Sheena'
- 'Orla'
- 'Vicki'
- 'Madeleine'
- 'Eudora'
- 'Julianna'
- 'Fiona'
- 'Deja'
- 'Oriana'
- 'Asma'
- 'Kiara'
- 'Chantelle'
- 'Rachael'
- 'Honor'
- 'Ariana'
- 'Safire'
- 'Josephine'
- 'Seren'
- 'Trinity'
- 'Cristal'
- 'Calliope'
- 'Azalea'
- 'Annika'
- 'Clodagh'
- 'Roxy'
- 'Venus'
- 'Delanie'
- 'Dede'
- 'Kerry'
- 'Latoya'
- 'Aubreanna'
- 'Ingrid'
- 'Katniss'
- 'Kitty'
- 'Barbie'
- 'Tatiana'
- 'Niamh'
- 'Marybeth'
- 'Elvira'
- 'Rosa'
- 'Paulette'
- 'Gillian'
- 'Marian'
- 'Aoibheann'
- 'Abrianna'
- 'Aspen'
- 'Alaska'
- 'Leora'
- 'Leela'
- 'Belinda'
- 'Danika'
- 'Arya'
- 'Francesca'
- 'Latoya'
- 'Kassie'
- 'Kinley'
- 'Isadora'
- 'Lexis'
- 'Violet'
- 'Lydia'
- 'Cierra'
- 'Nishka'
- 'Willow'
- 'Salome'
- 'Phoebe'
- 'Lexis'
- 'Leela'
- 'Aubreanna'
- 'Kyra'
- 'Taryn'
- 'Susan'
- 'Jana'
- 'Adalyn'
- 'Sian'
- 'Rose'
- 'Adelene'
- 'Dina'
- 'Briella'
- 'Chantelle'
- 'Fabrizia'
- 'Nikita'
- 'Eileen'
- 'Braylee'
- 'Amelia'
- 'Ashlie'
- 'Fiona'
- 'Cece'
- 'Lee'
- 'Arisha'
- 'Sky'
- 'Nichola'
- 'Katara'
- 'Charlette'
- 'Katlyn'
- 'Bethany'
- 'Rosalina'
- 'Sorrel'
- 'Sarina'
- 'Liza'
- 'Riley'
- 'Carlynn'
- 'Katelynn'
- 'Corina'
- 'Greta'
- 'Harper'
- 'Liana'
- 'Sydney'
- 'Vicky'
- 'Blythe'
- 'Bloom'
- 'Janice'
- 'Thalia'
- 'Bobbie'
- 'Jazmine'
- 'Bobby'
- 'Philomena'
- 'Montana'
- 'Nia'
- 'Brenna'
- 'Gracelyn'
- 'Lainey'
- 'Queenie'
- 'Rene'
- 'Lana'
- 'Leyla'
- 'Elida'
- 'Brook'
- 'Fia'
- 'Sariya'
- 'Candace'
- 'Asia'
- 'Taliyah'
- 'Gert'
- 'Annalisa'
- 'Flo'
- 'Carmen'
- 'Alanna'
- 'Benita'
- 'Zoe'
- 'Waverley'
- 'Joy'
- 'Vivienne'
- 'Emilie'
- 'Shawnette'
- 'Tessa'
- 'Nova'
- 'Sammie'
- 'Eabha'
- 'Susanne'
- 'Malina'
- 'Brittney'
- 'Phyllis'
- 'Avery'
- 'Danette'
- 'Allie'
- 'Baylee'
- 'Lyndsey'
- 'Jennie'
- 'Harriet'
- 'Mackenzie'
- 'Gloria'
- 'Tina'
- 'Roisin'
- 'Amberly'
- 'Meg'
- 'Morgana'
- 'Zelda'
- 'Kendra'
- 'Irena'
- 'Sammy'
- 'Seren'
- 'Winnie'
- 'Kalea'
- 'Yula'
- 'Nellie'
- 'Maybell'
- 'Lilah'
- 'Isis'
- 'Irina'
- 'Beverly'
- 'Lizzy'
- 'Campbell'
- 'Hermione'
- 'Kassidy'
- 'Joni'
- 'Rikki'
- 'Athalia'
- 'Campbell'
- 'Zendaya'
- 'Gayle'
- 'Judith'
- 'Xia'
- 'Honour'
- 'Chelsea'
- 'Leilani'
- 'Eliana'
- 'Merida'
- 'Gertrude'
- 'Debbie'