name: BeeNames
main: me.hashashin.BeeNames.BeeNames
version: 0.1
author: hashashin
api-version: 1.15
description: >
            Plugin to name Bees as soon as they spawn based on a dictionary
commands:
  reload:
    description: Reload the config file
    aliases: [beereload,beenamesreload]
    permission: beenames.reload
    permission-message: You've no permission to use this command!
    usage: /<command>
    default: op